### ISSUE TITLE
Replace glide with godep as the dependency manager

### ISSUE THREAD

**Issue by cmlicata** [inadarei/justgo#4]
## Summary / Context
Godep has officially become public and deemed safe for production as the standard Go dependency tool.  
As such, Gophers are encouraged to migrate their existing projects over to Godep.  Sam Boyer and the rest of the Godep team has made it very easy to do so:  
>during `dep init` configuration from other dependency managers is detected and imported, unless `-skip-tools` is specified.

## Current Behavior

Currently, justgo is using Glide as its dependency manager, which presents many issues and pain points.  

## Suggestion for a Solution

It would be best to migrate sooner rather than later, since we want to be able to build out the project without concern for dependency management any longer.

**Comment by inadarei** [comment]
NICE! If you open a PR - I will review it right after the vacation :)

Thank you!
